### ISSUE TITLE
[Bug] "TypeError: this.getOptions is not a function" with Next 10.0.9

### ISSUE THREAD

**Issue by JaeWangL** [SolidZORO/next-plugin-antd-less#30]
First of all, Thnak you for your awesome effort
I'm using this pakcage with next 10.0.9. But, when I started my app below message is showed

```
./node_modules/antd/lib/style/index.less ((webpack)/css-loader/cjs.js??ref--5-oneOf-3-1!(webpack)/postcss-loader/cjs.js??ref--5-oneOf-3-2!(webpack)/resolve-url-loader??ref--5-oneOf-3-3!./node_modules/less-loader/dist/cjs.js??ref--5-oneOf-3-4!./node_modules/antd/lib/style/index.less)
TypeError: this.getOptions is not a function
```

My package

```
    "@ant-design/icons": "^4.5.0",
    "@emotion/react": "^11.1.5",
    "@emotion/styled": "^11.1.5",
    "@tanem/react-nprogress": "^3.0.58",
    "antd": "^4.14.0",
    "axios": "^0.21.1",
    "babel-plugin-import": "^1.13.3",
    "bootstrap": "^4.6.0",
    "immer": "^8.0.1",
    "less": "^4.1.1",
    "next": "^10.0.9",
    "next-i18next": "^8.1.1",
    "next-redux-wrapper": "^6.0.2",
    "next-seo": "^4.20.0",
    "react": "^17.0.1",
    "react-bootstrap": "^1.5.2",
    "react-dom": "^17.0.1",
    "react-fast-compare": "^3.2.0",
    "react-icons": "^4.2.0",
    "react-redux": "^7.2.2",
    "redux": "^4.0.5",
    "redux-saga": "^1.1.3",
    "sass": "^1.32.8"
"next-plugin-antd-less": "^0.3.0",
```

**Comment by SolidZORO** [comment]
https://github.com/SolidZORO/next-plugin-antd-less/issues/20

https://github.com/SolidZORO/next-plugin-antd-less/issues/17

Do these issues help you?

**Comment by JaeWangL** [comment]
If I downgrade less-loader to 7.3.0, work well with this package v0.3.0
But less-loader v8.0.0, still not work

**Comment by SolidZORO** [comment]
This is as expected, please don't use less-loader 8.0, later I'm compatible with less-loader 8.0, but no plans for now.

**Comment by JaeWangL** [comment]
> This is as expected, please don't use less-loader 8.0, later I'm compatible with less-loader 8.0, but no plans for now.

Ok sir. Thank you!
